# Generated by Django 4.2 on 2025-05-25 23:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'ordering': ['lesson__chapter__order', 'lesson__order'], 'verbose_name': 'پیشرفت درس', 'verbose_name_plural': 'پیشرفت\u200cهای درس'},
        ),
        migrations.RemoveIndex(
            model_name='lessonprogress',
            name='course_less_user_id_cf104f_idx',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین فعالیت'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت\u200cهای کاربر'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز درس'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'شروع نشده'), ('in_progress', 'در حال یادگیری'), ('completed', 'تکمیل شده')], default='not_started', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', 'lesson', 'status'], name='course_less_user_id_b381b3_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['completion_date'], name='course_less_complet_41e18d_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['last_activity'], name='course_less_last_ac_52c173_idx'),
        ),
    ]
