# Generated by Django 4.2 on 2025-05-25 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('summary', models.TextField(blank=True, verbose_name='خلاصه')),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/articles/', verbose_name='تصویر شاخص')),
                ('thumbnail', models.ImageField(blank=True, upload_to='blog/thumbnails/', verbose_name='کاور')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'نشان\u200cشده مقاله',
                'verbose_name_plural': 'نشان\u200cشده\u200cهای مقاله',
            },
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پسند مقاله',
                'verbose_name_plural': 'پسندهای مقاله',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('thumbnail', models.ImageField(blank=True, upload_to='media/thumbnails/', verbose_name='تصویر شاخص')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('private', 'خصوصی')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('file', models.FileField(upload_to='media/files/', verbose_name='فایل')),
                ('file_type', models.CharField(choices=[('document', 'سند'), ('image', 'تصویر'), ('archive', 'آرشیو'), ('other', 'سایر')], max_length=10, verbose_name='نوع فایل')),
                ('file_size', models.PositiveIntegerField(help_text='حجم به بایت', verbose_name='حجم فایل')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دانلود')),
                ('is_free', models.BooleanField(default=True, verbose_name='دانلود رایگان')),
            ],
            options={
                'verbose_name': 'فایل',
                'verbose_name_plural': 'فایل\u200cها',
            },
        ),
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('thumbnail', models.ImageField(blank=True, upload_to='media/thumbnails/', verbose_name='تصویر شاخص')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('private', 'خصوصی')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('stream_url', models.URLField(blank=True, verbose_name='آدرس پخش')),
                ('stream_key', models.CharField(blank=True, max_length=100, verbose_name='کلید پخش')),
                ('scheduled_start', models.DateTimeField(verbose_name='زمان شروع برنامه\u200cریزی شده')),
                ('scheduled_end', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان برنامه\u200cریزی شده')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع واقعی')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان واقعی')),
                ('stream_status', models.CharField(choices=[('scheduled', 'برنامه\u200cریزی شده'), ('live', 'در حال پخش'), ('ended', 'پایان یافته'), ('cancelled', 'لغو شده')], default='scheduled', max_length=10, verbose_name='وضعیت پخش')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='پخش تکرار شونده')),
                ('max_viewers', models.PositiveIntegerField(default=0, verbose_name='حداکثر بازدیدکننده')),
                ('current_viewers', models.PositiveIntegerField(default=0, verbose_name='بازدیدکنندگان فعلی')),
            ],
            options={
                'verbose_name': 'پخش زنده',
                'verbose_name_plural': 'پخش\u200cهای زنده',
            },
        ),
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی رسانه',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای رسانه',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content', models.TextField(verbose_name='محتوا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
            ],
            options={
                'verbose_name': 'نظر رسانه',
                'verbose_name_plural': 'نظرات رسانه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('value', models.PositiveSmallIntegerField(help_text='امتیاز بین 1 تا 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'امتیاز رسانه',
                'verbose_name_plural': 'امتیازهای رسانه',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('thumbnail', models.ImageField(blank=True, upload_to='media/thumbnails/', verbose_name='تصویر شاخص')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('private', 'خصوصی')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('audio_file', models.FileField(upload_to='media/podcasts/', verbose_name='فایل صوتی')),
                ('duration', models.DurationField(verbose_name='مدت زمان')),
                ('episode_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='شماره قسمت')),
                ('season_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='شماره فصل')),
                ('transcript', models.TextField(blank=True, verbose_name='متن پیاده\u200cشده')),
            ],
            options={
                'verbose_name': 'پادکست',
                'verbose_name_plural': 'پادکست\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(help_text='Rating value between 1 and 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'rating',
                'verbose_name_plural': 'ratings',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('thumbnail', models.ImageField(blank=True, upload_to='media/thumbnails/', verbose_name='تصویر شاخص')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('private', 'خصوصی')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('video_type', models.CharField(choices=[('youtube', 'یوتیوب'), ('vimeo', 'ویمیو'), ('upload', 'آپلود شده'), ('embedded', 'افلود شده')], default='embedded', max_length=10, verbose_name='نوع ویدیو')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='آدرس ویدیو')),
                ('video_embed', models.TextField(blank=True, null=True, verbose_name='امبد')),
                ('video_file', models.FileField(blank=True, upload_to='media/videos/', verbose_name='فایل ویدیو')),
                ('duration', models.DurationField(verbose_name='مدت زمان')),
                ('is_premium', models.BooleanField(default=False, verbose_name='محتوای ویژه')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیوها',
            },
        ),
    ]
