# Generated by Django 4.2 on 2025-05-25 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='video',
            name='bookmarks',
            field=models.ManyToManyField(related_name='%(class)s_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='نشان\u200cشده\u200cها'),
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.mediacategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(related_name='%(class)s_likes', to=settings.AUTH_USER_MODEL, verbose_name='پسندها'),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tag', verbose_name='برچسب\u200cها'),
        ),
        migrations.AddField(
            model_name='rating',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='blog.article', verbose_name='article'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_ratings', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='bookmarks',
            field=models.ManyToManyField(related_name='%(class)s_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='نشان\u200cشده\u200cها'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.mediacategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='likes',
            field=models.ManyToManyField(related_name='%(class)s_likes', to=settings.AUTH_USER_MODEL, verbose_name='پسندها'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tag', verbose_name='برچسب\u200cها'),
        ),
        migrations.AddField(
            model_name='mediarating',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='mediarating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_ratings', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='mediacomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_comments', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='mediacomment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='mediacomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.mediacomment', verbose_name='نظر والد'),
        ),
        migrations.AddField(
            model_name='mediacategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='blog.mediacategory', verbose_name='دسته\u200cبندی والد'),
        ),
        migrations.AddField(
            model_name='livestream',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='livestream',
            name='bookmarks',
            field=models.ManyToManyField(related_name='%(class)s_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='نشان\u200cشده\u200cها'),
        ),
        migrations.AddField(
            model_name='livestream',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.mediacategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='livestream',
            name='likes',
            field=models.ManyToManyField(related_name='%(class)s_likes', to=settings.AUTH_USER_MODEL, verbose_name='پسندها'),
        ),
        migrations.AddField(
            model_name='livestream',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tag', verbose_name='برچسب\u200cها'),
        ),
        migrations.AddField(
            model_name='file',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='file',
            name='bookmarks',
            field=models.ManyToManyField(related_name='%(class)s_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='نشان\u200cشده\u200cها'),
        ),
        migrations.AddField(
            model_name='file',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.mediacategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='file',
            name='likes',
            field=models.ManyToManyField(related_name='%(class)s_likes', to=settings.AUTH_USER_MODEL, verbose_name='پسندها'),
        ),
        migrations.AddField(
            model_name='file',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tag', verbose_name='برچسب\u200cها'),
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article', verbose_name='مقاله'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment', verbose_name='نظر والد'),
        ),
        migrations.AddField(
            model_name='articlelike',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='مقاله'),
        ),
        migrations.AddField(
            model_name='articlelike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='articlebookmark',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='مقاله'),
        ),
        migrations.AddField(
            model_name='articlebookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='article',
            name='bookmarks',
            field=models.ManyToManyField(related_name='bookmarked_articles', through='blog.ArticleBookmark', to=settings.AUTH_USER_MODEL, verbose_name='نشان\u200cشده\u200cها'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(related_name='liked_articles', through='blog.ArticleLike', to=settings.AUTH_USER_MODEL, verbose_name='پسندها'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='blog.tag', verbose_name='برچسب\u200cها'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'article')},
        ),
        migrations.AddIndex(
            model_name='mediarating',
            index=models.Index(fields=['content_type', 'object_id'], name='blog_mediar_content_4bb78d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mediarating',
            unique_together={('user', 'content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='mediacomment',
            index=models.Index(fields=['content_type', 'object_id'], name='blog_mediac_content_8702a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='articlelike',
            unique_together={('user', 'article')},
        ),
        migrations.AlterUniqueTogether(
            name='articlebookmark',
            unique_together={('user', 'article')},
        ),
    ]
